import { motion } from "framer-motion";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import {
  Bot, ShoppingBag, BookOpen, Users, Mail, Zap,
  BarChart2, Link2, Globe, Shield, CreditCard, Headphones,
  ArrowRight, Check, Play, Sparkles, TrendingUp, Target, Star
} from "lucide-react";

const features = [
  {
    icon: ShoppingBag, color: "#22c55e", tag: "DIGITAL PRODUCTS",
    title: "Creator Store & Checkout",
    desc: "Launch your digital product store in minutes. Sell ebooks, templates, presets, Notion packs, Lightroom filters, and more — with built-in checkout, instant payouts, and 0% transaction fees.",
    bullets: ["Unlimited product listings", "One-click checkout pages", "Instant payouts via Stripe & PayPal", "Custom thank-you pages", "Upsells & order bumps"],
    mockup: [
      { name: "Ultimate Notion Template Pack", price: "$47", sales: "342 sales" },
      { name: "Freelancer Business Kit", price: "$97", sales: "128 sales" },
      { name: "Social Media Masterclass", price: "$197", sales: "89 sales" },
    ]
  },
  {
    icon: BookOpen, color: "#3b82f6", tag: "COURSES",
    title: "AI Course Builder",
    desc: "Create and sell online courses without spending weeks on content. Our AI generates curriculum, lesson scripts, quizzes, and a full sales page — you record, we host it.",
    bullets: ["AI curriculum generator", "Drip content scheduling", "Video hosting included", "Progress tracking & certificates", "Student community built-in"],
    mockup: null
  },
  {
    icon: Users, color: "#a855f7", tag: "MEMBERSHIPS",
    title: "Paid Community Builder",
    desc: "Build a thriving paid community where members get exclusive content, live sessions, and direct access to you. Charge monthly or annually — recurring revenue on autopilot.",
    bullets: ["Gated content areas", "Monthly & annual billing", "Live session integration", "Discussion boards", "Member analytics"],
    mockup: null
  },
  {
    icon: Target, color: "#f59e0b", tag: "FUNNELS",
    title: "AI Funnel Builder",
    desc: "Build high-converting sales funnels in minutes. Landing pages, upsell flows, email sequences — all generated by AI and optimized for conversion.",
    bullets: ["Drag-and-drop funnel builder", "AI copywriting assistant", "A/B split testing", "Conversion analytics", "100+ proven templates"],
    mockup: null
  },
  {
    icon: Mail, color: "#ef4444", tag: "EMAIL MARKETING",
    title: "Email Marketing & CRM",
    desc: "Grow your audience and sell on autopilot. Send broadcast emails, build automated sequences, and manage all your leads from one inbox.",
    bullets: ["Visual email builder", "Automation workflows", "Segmentation & tags", "Up to 100k contacts on Pro", "99%+ deliverability rate"],
    mockup: null
  },
  {
    icon: Bot, color: "#22c55e", tag: "AI TOOLS",
    title: "AI Content & Chatbot Suite",
    desc: "A full suite of AI tools built for creators — generate product descriptions, write course content, build chatbots that sell for you 24/7, and auto-reply to DMs.",
    bullets: ["AI product description writer", "AI course generator", "AI chatbot builder", "AI email writer", "AI social media captions"],
    mockup: null
  },
];

const extras = [
  { icon: Link2, title: "Link in Bio", desc: "A beautiful profile page with all your products, links, and social handles in one place." },
  { icon: Globe, title: "Custom Domains", desc: "Connect your own domain to your store, courses, and funnels." },
  { icon: BarChart2, title: "Deep Analytics", desc: "Track revenue, conversions, student progress, and email open rates in real time." },
  { icon: Shield, title: "Content Protection", desc: "DRM-backed video protection and paywall enforcement on all content." },
  { icon: CreditCard, title: "0% Transaction Fees", desc: "Keep everything you earn. No platform cuts, ever." },
  { icon: Headphones, title: "Priority Support", desc: "Live chat, email support, and a dedicated account manager on Pro." },
  { icon: Zap, title: "Zapier & API", desc: "Connect EarnStack to 5,000+ apps and build custom automations." },
  { icon: TrendingUp, title: "Affiliate Program", desc: "Let others promote your products and pay them automatically on each sale." },
];

// Different social proof for Features — vertical staggered testimonials
const testimonials = [
  { name: "Layla M.", role: "Online Coach", avatar: "L", color: "#22c55e", quote: "I launched 3 courses, built a community, and made $18k in my first month — all without a developer.", result: "$18k first month" },
  { name: "Chris D.", role: "Notion Creator", avatar: "C", color: "#3b82f6", quote: "EarnStack replaced 5 different tools for me. My Notion templates now sell on autopilot 24/7.", result: "5 tools → 1 platform" },
  { name: "Nadia S.", role: "Fitness Influencer", avatar: "N", color: "#a855f7", quote: "My paid community hit $6k MRR in 60 days. The membership builder made it insanely simple.", result: "$6k MRR in 60 days" },
  { name: "Omar K.", role: "Marketing Consultant", avatar: "O", color: "#f59e0b", quote: "The AI funnel builder built a $50k launch funnel in 30 minutes. That's not an exaggeration.", result: "$50k funnel in 30 min" },
  { name: "Rin T.", role: "YouTube Educator", avatar: "R", color: "#ef4444", quote: "The AI course generator wrote my entire curriculum before lunch. I just recorded the lessons.", result: "Full course in 1 day" },
  { name: "Ben A.", role: "Freelance Designer", avatar: "B", color: "#0ea5e9", quote: "I was skeptical about 'all-in-one' tools. EarnStack is the first one that actually delivers everything.", result: "4.9★ — loves it" },
];

const containerVars = { hidden: {}, show: { transition: { staggerChildren: 0.1 } } };
const itemVars = { hidden: { opacity: 0, y: 40 }, show: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut" } } };

export default function Features() {
  return (
    <div className="min-h-screen bg-[#0E0E0E] text-white w-full overflow-x-hidden font-sans">
      <Navbar />

      {/* Hero with decorative glows */}
      <section className="relative pt-20 pb-16 px-6 text-center max-w-4xl mx-auto overflow-hidden">
        <div className="absolute -top-24 left-1/2 -translate-x-1/2 w-[700px] h-[300px] bg-[#22c55e]/7 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute top-8 right-8 text-[#22c55e] opacity-40 animate-pulse text-2xl select-none">✦</div>
        <div className="absolute top-24 left-12 text-[#eab308] opacity-25 animate-pulse text-xl select-none">✦</div>
        <div className="absolute bottom-0 right-24 text-gray-500 opacity-20 text-3xl select-none">✧</div>

        <motion.div variants={containerVars} initial="hidden" animate="show" className="relative z-10">
          <motion.span variants={itemVars}
            className="text-xs text-[#22c55e] uppercase tracking-widest font-semibold border border-[#22c55e]/30 px-3 py-1 rounded-full inline-block mb-6">
            Every Feature You Need
          </motion.span>
          <motion.h1 variants={itemVars} className="text-5xl md:text-6xl font-display font-bold text-white leading-tight mb-6">
            One Platform.<br />
            <span className="text-[#22c55e]">Infinite Income Streams.</span>
          </motion.h1>
          <motion.p variants={itemVars} className="text-xl text-gray-400 max-w-2xl mx-auto mb-10">
            From digital products to AI-powered courses, communities, funnels, and email marketing — everything a modern creator needs in one place.
          </motion.p>
          <motion.div variants={itemVars} className="flex flex-wrap gap-4 justify-center">
            <motion.button whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }}
              className="bg-[#22c55e] text-black font-bold px-8 py-3.5 rounded-full text-base shadow-[0_0_24px_rgba(34,197,94,0.3)] hover:bg-[#16a34a] transition-colors flex items-center gap-2">
              Start Free <ArrowRight size={16} />
            </motion.button>
            <motion.button whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }}
              className="bg-white/10 text-white font-bold px-8 py-3.5 rounded-full text-base border border-white/10 hover:bg-white/20 transition-colors flex items-center gap-2">
              <Play size={14} /> Watch Demo
            </motion.button>
          </motion.div>
        </motion.div>
      </section>

      {/* Main Features */}
      <section className="py-12 px-6 max-w-7xl mx-auto w-full space-y-24">
        {features.map((f, i) => {
          const Icon = f.icon;
          const isEven = i % 2 === 0;
          return (
            <motion.div key={i}
              initial={{ opacity: 0, y: 50 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className={`flex flex-col ${isEven ? "md:flex-row" : "md:flex-row-reverse"} gap-12 items-center`}
            >
              <div className="flex-1">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: f.color + "20" }}>
                    <Icon size={20} style={{ color: f.color }} />
                  </div>
                  <span className="text-xs font-bold tracking-widest" style={{ color: f.color }}>{f.tag}</span>
                </div>
                <h2 className="text-3xl md:text-4xl font-display font-bold text-white mb-4">{f.title}</h2>
                <p className="text-gray-400 text-lg leading-relaxed mb-6">{f.desc}</p>
                <ul className="space-y-3">
                  {f.bullets.map((b, bi) => (
                    <li key={bi} className="flex items-center gap-3 text-sm text-gray-300">
                      <div className="w-5 h-5 rounded-full bg-[#22c55e]/20 flex items-center justify-center shrink-0">
                        <Check size={11} className="text-[#22c55e]" />
                      </div>
                      {b}
                    </li>
                  ))}
                </ul>
                <motion.button whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }}
                  className="mt-8 flex items-center gap-2 text-sm font-bold hover:gap-3 transition-all" style={{ color: f.color }}>
                  Learn more <ArrowRight size={14} />
                </motion.button>
              </div>

              <div className="flex-1 w-full">
                <div className="rounded-2xl border border-white/10 bg-[#141414] overflow-hidden shadow-[0_20px_60px_rgba(0,0,0,0.5)]">
                  <div className="flex items-center gap-2 px-4 py-3 border-b border-white/10 bg-[#0E0E0E]">
                    <span className="w-2.5 h-2.5 rounded-full bg-red-500/70" />
                    <span className="w-2.5 h-2.5 rounded-full bg-yellow-500/70" />
                    <span className="w-2.5 h-2.5 rounded-full bg-green-500/70" />
                    <span className="ml-3 text-xs text-gray-600">EarnStack · {f.tag}</span>
                  </div>
                  <div className="p-6">
                    {f.mockup ? (
                      <div className="space-y-3">
                        <div className="flex items-center justify-between mb-4">
                          <span className="text-sm font-bold text-white">My Products</span>
                          <button className="text-xs bg-[#22c55e] text-black font-bold px-3 py-1 rounded-lg">+ Add Product</button>
                        </div>
                        {f.mockup.map((row, ri) => (
                          <div key={ri} className="flex items-center gap-3 rounded-xl bg-white/5 border border-white/5 px-4 py-3">
                            <ShoppingBag size={14} className="text-[#22c55e] shrink-0" />
                            <span className="text-sm text-gray-300 flex-1">{row.name}</span>
                            <span className="text-sm font-bold text-[#22c55e]">{row.price}</span>
                            <span className="text-xs text-gray-500">{row.sales}</span>
                          </div>
                        ))}
                        <div className="mt-4 bg-gradient-to-r from-[#22c55e] to-[#16a34a] rounded-xl p-3 text-center">
                          <span className="text-black font-bold text-sm">$4,820 earned this month 🚀</span>
                        </div>
                      </div>
                    ) : (
                      <div className="flex flex-col gap-4">
                        <div className="rounded-xl bg-white/5 border border-white/5 p-4">
                          <div className="flex items-center gap-2 mb-3">
                            <div className="w-6 h-6 rounded-lg flex items-center justify-center" style={{ background: f.color + "30" }}>
                              <Icon size={12} style={{ color: f.color }} />
                            </div>
                            <span className="text-xs font-semibold" style={{ color: f.color }}>AI Assistant</span>
                          </div>
                          <p className="text-xs text-gray-400 leading-relaxed">
                            I'll help you build your {f.title.toLowerCase()} in minutes. What would you like to create today?
                          </p>
                        </div>
                        <div className="rounded-xl bg-white/5 border border-white/5 p-4 space-y-2">
                          {f.bullets.slice(0, 3).map((b, bi) => (
                            <div key={bi} className="flex items-center gap-2 text-xs text-gray-400">
                              <div className="w-1.5 h-1.5 rounded-full" style={{ background: f.color }} />
                              {b}
                            </div>
                          ))}
                        </div>
                        <button className="w-full py-2.5 rounded-xl font-bold text-sm text-black transition-colors" style={{ background: f.color }}>
                          Get Started Free →
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </motion.div>
          );
        })}
      </section>

      {/* Testimonials — staggered fade-in grid (different from home marquee) */}
      <section className="py-24 px-6 max-w-7xl mx-auto w-full">
        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
          className="text-center mb-14">
          <span className="text-xs text-[#22c55e] uppercase tracking-widest font-semibold border border-[#22c55e]/30 px-3 py-1 rounded-full inline-block mb-4">Creator Stories</span>
          <h2 className="text-3xl md:text-4xl font-display font-bold text-white mb-3">Real creators. Real results.</h2>
          <p className="text-gray-400">Here's what happened when they switched to EarnStack.</p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {testimonials.map((t, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 40, scale: 0.96 }}
              whileInView={{ opacity: 1, y: 0, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1, duration: 0.5 }}
              whileHover={{ y: -6, transition: { duration: 0.2 } }}
              className="rounded-2xl border border-white/10 bg-[#141414] p-6 flex flex-col gap-4 cursor-default"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full flex items-center justify-center text-sm font-bold" style={{ background: t.color + "25", color: t.color }}>
                  {t.avatar}
                </div>
                <div>
                  <p className="text-sm font-bold text-white">{t.name}</p>
                  <p className="text-xs text-gray-500">{t.role}</p>
                </div>
                <div className="ml-auto flex gap-0.5">
                  {[...Array(5)].map((_, si) => <Star key={si} size={10} className="text-[#eab308]" fill="#eab308" />)}
                </div>
              </div>
              <p className="text-sm text-gray-300 leading-relaxed italic">"{t.quote}"</p>
              <div className="mt-auto pt-3 border-t border-white/5">
                <span className="text-xs font-bold px-2.5 py-1 rounded-full" style={{ background: t.color + "15", color: t.color }}>
                  ✓ {t.result}
                </span>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Extra Features Grid */}
      <section className="py-24 px-6 max-w-7xl mx-auto w-full">
        <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
          className="text-center mb-14">
          <h2 className="text-3xl md:text-4xl font-display font-bold text-white mb-4">And so much more</h2>
          <p className="text-gray-400 text-lg">Everything you need to run a serious creator business.</p>
        </motion.div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-5">
          {extras.map((e, i) => {
            const Icon = e.icon;
            return (
              <motion.div key={i}
                initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
                transition={{ delay: i * 0.05 }}
                className="rounded-2xl border border-white/8 bg-[#141414] p-5 hover:border-[#22c55e]/30 transition-colors group">
                <div className="w-10 h-10 rounded-xl bg-[#22c55e]/10 flex items-center justify-center mb-4 group-hover:bg-[#22c55e]/20 transition-colors">
                  <Icon size={18} className="text-[#22c55e]" />
                </div>
                <h3 className="font-bold text-white text-sm mb-2">{e.title}</h3>
                <p className="text-xs text-gray-500 leading-relaxed">{e.desc}</p>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-6 text-center relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-[#22c55e]/5 pointer-events-none" />
        <motion.div initial={{ opacity: 0, scale: 0.95 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ duration: 0.6 }} className="relative z-10">
          <Sparkles size={32} className="text-[#22c55e] mx-auto mb-4" />
          <h2 className="text-4xl md:text-5xl font-display font-bold text-white mb-4">Ready to start earning?</h2>
          <p className="text-gray-400 text-lg mb-8 max-w-xl mx-auto">Join 50,000+ creators. Start free, no credit card required.</p>
          <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
            className="bg-[#22c55e] text-black font-bold px-10 py-4 rounded-full text-lg shadow-[0_0_30px_rgba(34,197,94,0.3)] hover:bg-[#16a34a] transition-colors">
            Start Building Free →
          </motion.button>
          <p className="text-gray-600 text-sm mt-4">0% transaction fees · Cancel anytime</p>
        </motion.div>
      </section>

      <Footer />
    </div>
  );
}
